import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import notification from "@/components/notification";

import { api } from "@/utils/api";
import { useEffect } from "react";
import Sidebar from "@/components/Sidebar";

export default function Home() {
  const { data: sessionData } = useSession();
  // localStorage.theme = "light";
  // localStorage.removeItem("theme");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Sidebar />
      </>
    </>
  );
}
